#include "stack.h"
#include <assert.h>
#include <stdlib.h>


/****** Pre-defination for test suits. ******/
static void t_arrstack_create ();
static void t_arrstack_push ();
static void t_arrstack_release ();

static void _free_hook1 (const void*);
/* We use this array to store freed element
 * on testing release function. */
static int _freed_elm [1024] = {0, };
static int _arr_index = 0;


/* Main test entry. */
int main (int argc, char* argv []) {
	t_arrstack_create ();
	t_arrstack_release ();
	t_arrstack_push ();
	return 0;
}


/******* Implementation for each test suit. ******/

static void t_arrstack_create () {
	/* 1024 stack. */
	parrstack stack = arrstack_create (1024);
	assert (stack != NULL);
	assert (stack -> top == 0);
	assert (stack -> base != NULL);
	assert (stack -> capacity == 1024);
	arrstack_release (stack, NULL);

	/* 0 stack. */
	stack = arrstack_create (0);
	assert (stack != NULL);
	assert (stack -> top == 0);
	assert (stack -> base != NULL);
	assert (stack -> capacity == DEFAULT_STACK_CAPACITY);
	arrstack_release (stack, NULL);

	/* -3232 stack. */
	stack = arrstack_create (-3232);
	assert (stack != NULL);
	assert (stack -> top == 0);
	assert (stack -> base != NULL);
	assert (stack -> capacity == DEFAULT_STACK_CAPACITY);
	arrstack_release (stack, NULL);

}


static void t_arrstack_push () {
	int i = 0;
	parrstack stack = arrstack_create (128);
	assert (stack != NULL);

	/* Note: Because the element pointer must
	 * not be NULL, so if we push a integer 
	 * zero, it will be treated as NULL. so
	 * we ignore this element for testing. */
	for (; i < 64; ++ i)
		arrstack_push (stack, (void*) (i + 1));
	
	assert (stack -> top == 64);
	assert (stack -> capacity == 128);

	for (i = 0; i < 64; ++ i)
		assert ((stack -> base) [i] == (void*) (i + 1));

	arrstack_release (stack, NULL);
}


/* Used by release function testing. */
static void _free_hook1 (const void* _e) {
	_freed_elm [_arr_index ++] = (int) _e;
}

static void t_arrstack_release () {
	int i = 0, n;
	_arr_index = 0;
	parrstack stack = arrstack_create (64);
	assert (stack != NULL);

	/* Sequence : f(n) = n * 2 + 32 */
	for (i = 1; i <= 64; ++ i)
		arrstack_push (stack, (void*) ((i << 1) + 32));
	
	assert (stack -> top == 64);
	assert (stack -> capacity == 64);

	arrstack_release (stack, _free_hook1);
	/* That is to say, _free_hook1() have
	 * been invoked 64 times. */
	assert (_arr_index == 64);
	assert (_freed_elm [_arr_index]== 0);

	/* To test each element being freed by
	 * user-defined callback. 
	 *
	 * Note: we have to reversed the sequence 
	 * generated by f(n) = n * 32 + 32 due to 
	 * the implementation of stack release 
	 * function. */
	for (i = 0, n = 64; i < 64; ++ i, -- n)
		assert (_freed_elm [i] == ((n << 1) + 32));
}





